---
# This playbook contains common plays that will be run on all nodes.

- name: refresh the master package lists
  pacman: name=pacman state=installed update_cache=yes
  tags: pacman

- name: install base packages package binary and its dependencies
  pacman: name={{ item }} state=installed
  with_items:
    - vim
    - tmux
    - virtualbox-guest-modules
    - xterm
    - chromium

- include: users.yml tags=users
- include: openssh.yml tags=ssh
- include: ntp.yml tags=ntp
- include: xfce.yml tags=awesome
- include: vbox.yml tags=virtualbox
- include: local_config.yml tags=local_config
